/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Customer {
  'name' : string,
  'totalPurchases' : bigint,
  'totalSpent' : number,
  'phone' : string,
  'totalDiscount' : number,
}
export interface DeadPlant {
  'date' : Time,
  'deadQuantity' : bigint,
  'purchasePriceEach' : number,
  'totalLoss' : number,
  'productId' : bigint,
  'productName' : string,
  'notes' : [] | [string],
  'photo' : [] | [string],
  'reason' : string,
}
export interface Expense {
  'date' : Time,
  'description' : string,
  'paymentMode' : string,
  'category' : string,
  'amount' : number,
}
export interface Product {
  'id' : bigint,
  'status' : ProductStatus,
  'purchasePrice' : number,
  'stockQty' : bigint,
  'name' : string,
  'color' : [] | [string],
  'size' : [] | [string],
  'parentPlant' : [] | [bigint],
  'sellingPrice' : number,
  'productType' : ProductType,
  'potType' : [] | [string],
  'category' : [] | [string],
  'image' : [] | [string],
  'propagationType' : [] | [string],
  'dateAdded' : Time,
}
export type ProductStatus = { 'active' : null } |
  { 'discontinued' : null } |
  { 'outOfStock' : null };
export type ProductType = { 'pot' : null } |
  { 'propagation' : null } |
  { 'plant' : null };
export interface Sale {
  'customerName' : [] | [string],
  'isWalkIn' : boolean,
  'customerPhone' : [] | [string],
  'date' : Time,
  'totalPaid' : number,
  'discountReason' : [] | [string],
  'discount' : number,
  'paymentMode' : string,
  'items' : Array<SaleItem>,
  'billNo' : string,
  'subtotal' : number,
  'savedMessage' : [] | [string],
}
export interface SaleItem {
  'total' : number,
  'productId' : bigint,
  'productName' : string,
  'quantity' : bigint,
  'price' : number,
}
export type Time = bigint;
export interface Worker {
  'salary' : number,
  'payments' : Array<WorkerPayment>,
  'joinDate' : Time,
  'name' : string,
  'phone' : string,
}
export interface WorkerPayment {
  'date' : Time,
  'paymentMode' : string,
  'amount' : number,
}
export interface _SERVICE {
  'addCustomer' : ActorMethod<[string, string], undefined>,
  'addDeadPlant' : ActorMethod<
    [
      Time,
      bigint,
      string,
      bigint,
      number,
      number,
      string,
      [] | [string],
      [] | [string],
    ],
    bigint
  >,
  'addExpense' : ActorMethod<[Time, string, string, number, string], bigint>,
  'addPlant' : ActorMethod<
    [string, [] | [string], number, number, bigint, [] | [string]],
    bigint
  >,
  'addPot' : ActorMethod<
    [string, string, string, string, number, number, bigint, [] | [string]],
    bigint
  >,
  'addPropagationPlant' : ActorMethod<
    [string, string, bigint, number, number, bigint, [] | [string]],
    bigint
  >,
  'addWorker' : ActorMethod<[string, string, number, Time], bigint>,
  'addWorkerPayment' : ActorMethod<[bigint, Time, number, string], undefined>,
  'createSale' : ActorMethod<
    [
      string,
      Time,
      [] | [string],
      [] | [string],
      boolean,
      Array<SaleItem>,
      number,
      number,
      [] | [string],
      number,
      string,
      [] | [string],
    ],
    undefined
  >,
  'deletePlant' : ActorMethod<[bigint], undefined>,
  'deletePot' : ActorMethod<[bigint], undefined>,
  'deletePropagationPlant' : ActorMethod<[bigint], undefined>,
  'getAllCustomers' : ActorMethod<[], Array<Customer>>,
  'getAllDeadPlants' : ActorMethod<[], Array<DeadPlant>>,
  'getAllExpenses' : ActorMethod<[], Array<Expense>>,
  'getAllPlants' : ActorMethod<[], Array<Product>>,
  'getAllPots' : ActorMethod<[], Array<Product>>,
  'getAllPropagationPlants' : ActorMethod<[], Array<Product>>,
  'getAllSales' : ActorMethod<[], Array<Sale>>,
  'getAllWorkers' : ActorMethod<[], Array<Worker>>,
  'getLowStockPlants' : ActorMethod<[], Array<Product>>,
  'updateCustomerStats' : ActorMethod<
    [string, bigint, number, number],
    undefined
  >,
  'updatePlant' : ActorMethod<
    [bigint, string, [] | [string], number, number, bigint, [] | [string]],
    undefined
  >,
  'updatePot' : ActorMethod<
    [
      bigint,
      string,
      string,
      string,
      string,
      number,
      number,
      bigint,
      [] | [string],
    ],
    undefined
  >,
  'updatePropagationPlant' : ActorMethod<
    [bigint, string, string, bigint, number, number, bigint, [] | [string]],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];