/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const SaleItem = IDL.Record({
  'total' : IDL.Float64,
  'productId' : IDL.Nat,
  'productName' : IDL.Text,
  'quantity' : IDL.Nat,
  'price' : IDL.Float64,
});
export const Customer = IDL.Record({
  'name' : IDL.Text,
  'totalPurchases' : IDL.Nat,
  'totalSpent' : IDL.Float64,
  'phone' : IDL.Text,
  'totalDiscount' : IDL.Float64,
});
export const DeadPlant = IDL.Record({
  'date' : Time,
  'deadQuantity' : IDL.Nat,
  'purchasePriceEach' : IDL.Float64,
  'totalLoss' : IDL.Float64,
  'productId' : IDL.Nat,
  'productName' : IDL.Text,
  'notes' : IDL.Opt(IDL.Text),
  'photo' : IDL.Opt(IDL.Text),
  'reason' : IDL.Text,
});
export const Expense = IDL.Record({
  'date' : Time,
  'description' : IDL.Text,
  'paymentMode' : IDL.Text,
  'category' : IDL.Text,
  'amount' : IDL.Float64,
});
export const ProductStatus = IDL.Variant({
  'active' : IDL.Null,
  'discontinued' : IDL.Null,
  'outOfStock' : IDL.Null,
});
export const ProductType = IDL.Variant({
  'pot' : IDL.Null,
  'propagation' : IDL.Null,
  'plant' : IDL.Null,
});
export const Product = IDL.Record({
  'id' : IDL.Nat,
  'status' : ProductStatus,
  'purchasePrice' : IDL.Float64,
  'stockQty' : IDL.Nat,
  'name' : IDL.Text,
  'color' : IDL.Opt(IDL.Text),
  'size' : IDL.Opt(IDL.Text),
  'parentPlant' : IDL.Opt(IDL.Nat),
  'sellingPrice' : IDL.Float64,
  'productType' : ProductType,
  'potType' : IDL.Opt(IDL.Text),
  'category' : IDL.Opt(IDL.Text),
  'image' : IDL.Opt(IDL.Text),
  'propagationType' : IDL.Opt(IDL.Text),
  'dateAdded' : Time,
});
export const Sale = IDL.Record({
  'customerName' : IDL.Opt(IDL.Text),
  'isWalkIn' : IDL.Bool,
  'customerPhone' : IDL.Opt(IDL.Text),
  'date' : Time,
  'totalPaid' : IDL.Float64,
  'discountReason' : IDL.Opt(IDL.Text),
  'discount' : IDL.Float64,
  'paymentMode' : IDL.Text,
  'items' : IDL.Vec(SaleItem),
  'billNo' : IDL.Text,
  'subtotal' : IDL.Float64,
  'savedMessage' : IDL.Opt(IDL.Text),
});
export const WorkerPayment = IDL.Record({
  'date' : Time,
  'paymentMode' : IDL.Text,
  'amount' : IDL.Float64,
});
export const Worker = IDL.Record({
  'salary' : IDL.Float64,
  'payments' : IDL.Vec(WorkerPayment),
  'joinDate' : Time,
  'name' : IDL.Text,
  'phone' : IDL.Text,
});

export const idlService = IDL.Service({
  'addCustomer' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'addDeadPlant' : IDL.Func(
      [
        Time,
        IDL.Nat,
        IDL.Text,
        IDL.Nat,
        IDL.Float64,
        IDL.Float64,
        IDL.Text,
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
      ],
      [IDL.Nat],
      [],
    ),
  'addExpense' : IDL.Func(
      [Time, IDL.Text, IDL.Text, IDL.Float64, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'addPlant' : IDL.Func(
      [
        IDL.Text,
        IDL.Opt(IDL.Text),
        IDL.Float64,
        IDL.Float64,
        IDL.Nat,
        IDL.Opt(IDL.Text),
      ],
      [IDL.Nat],
      [],
    ),
  'addPot' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Float64,
        IDL.Float64,
        IDL.Nat,
        IDL.Opt(IDL.Text),
      ],
      [IDL.Nat],
      [],
    ),
  'addPropagationPlant' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Float64,
        IDL.Float64,
        IDL.Nat,
        IDL.Opt(IDL.Text),
      ],
      [IDL.Nat],
      [],
    ),
  'addWorker' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Float64, Time],
      [IDL.Nat],
      [],
    ),
  'addWorkerPayment' : IDL.Func([IDL.Nat, Time, IDL.Float64, IDL.Text], [], []),
  'createSale' : IDL.Func(
      [
        IDL.Text,
        Time,
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Bool,
        IDL.Vec(SaleItem),
        IDL.Float64,
        IDL.Float64,
        IDL.Opt(IDL.Text),
        IDL.Float64,
        IDL.Text,
        IDL.Opt(IDL.Text),
      ],
      [],
      [],
    ),
  'deletePlant' : IDL.Func([IDL.Nat], [], []),
  'deletePot' : IDL.Func([IDL.Nat], [], []),
  'deletePropagationPlant' : IDL.Func([IDL.Nat], [], []),
  'getAllCustomers' : IDL.Func([], [IDL.Vec(Customer)], ['query']),
  'getAllDeadPlants' : IDL.Func([], [IDL.Vec(DeadPlant)], ['query']),
  'getAllExpenses' : IDL.Func([], [IDL.Vec(Expense)], ['query']),
  'getAllPlants' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getAllPots' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getAllPropagationPlants' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getAllSales' : IDL.Func([], [IDL.Vec(Sale)], ['query']),
  'getAllWorkers' : IDL.Func([], [IDL.Vec(Worker)], ['query']),
  'getLowStockPlants' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'updateCustomerStats' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Float64, IDL.Float64],
      [],
      [],
    ),
  'updatePlant' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Opt(IDL.Text),
        IDL.Float64,
        IDL.Float64,
        IDL.Nat,
        IDL.Opt(IDL.Text),
      ],
      [],
      [],
    ),
  'updatePot' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Float64,
        IDL.Float64,
        IDL.Nat,
        IDL.Opt(IDL.Text),
      ],
      [],
      [],
    ),
  'updatePropagationPlant' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Float64,
        IDL.Float64,
        IDL.Nat,
        IDL.Opt(IDL.Text),
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const SaleItem = IDL.Record({
    'total' : IDL.Float64,
    'productId' : IDL.Nat,
    'productName' : IDL.Text,
    'quantity' : IDL.Nat,
    'price' : IDL.Float64,
  });
  const Customer = IDL.Record({
    'name' : IDL.Text,
    'totalPurchases' : IDL.Nat,
    'totalSpent' : IDL.Float64,
    'phone' : IDL.Text,
    'totalDiscount' : IDL.Float64,
  });
  const DeadPlant = IDL.Record({
    'date' : Time,
    'deadQuantity' : IDL.Nat,
    'purchasePriceEach' : IDL.Float64,
    'totalLoss' : IDL.Float64,
    'productId' : IDL.Nat,
    'productName' : IDL.Text,
    'notes' : IDL.Opt(IDL.Text),
    'photo' : IDL.Opt(IDL.Text),
    'reason' : IDL.Text,
  });
  const Expense = IDL.Record({
    'date' : Time,
    'description' : IDL.Text,
    'paymentMode' : IDL.Text,
    'category' : IDL.Text,
    'amount' : IDL.Float64,
  });
  const ProductStatus = IDL.Variant({
    'active' : IDL.Null,
    'discontinued' : IDL.Null,
    'outOfStock' : IDL.Null,
  });
  const ProductType = IDL.Variant({
    'pot' : IDL.Null,
    'propagation' : IDL.Null,
    'plant' : IDL.Null,
  });
  const Product = IDL.Record({
    'id' : IDL.Nat,
    'status' : ProductStatus,
    'purchasePrice' : IDL.Float64,
    'stockQty' : IDL.Nat,
    'name' : IDL.Text,
    'color' : IDL.Opt(IDL.Text),
    'size' : IDL.Opt(IDL.Text),
    'parentPlant' : IDL.Opt(IDL.Nat),
    'sellingPrice' : IDL.Float64,
    'productType' : ProductType,
    'potType' : IDL.Opt(IDL.Text),
    'category' : IDL.Opt(IDL.Text),
    'image' : IDL.Opt(IDL.Text),
    'propagationType' : IDL.Opt(IDL.Text),
    'dateAdded' : Time,
  });
  const Sale = IDL.Record({
    'customerName' : IDL.Opt(IDL.Text),
    'isWalkIn' : IDL.Bool,
    'customerPhone' : IDL.Opt(IDL.Text),
    'date' : Time,
    'totalPaid' : IDL.Float64,
    'discountReason' : IDL.Opt(IDL.Text),
    'discount' : IDL.Float64,
    'paymentMode' : IDL.Text,
    'items' : IDL.Vec(SaleItem),
    'billNo' : IDL.Text,
    'subtotal' : IDL.Float64,
    'savedMessage' : IDL.Opt(IDL.Text),
  });
  const WorkerPayment = IDL.Record({
    'date' : Time,
    'paymentMode' : IDL.Text,
    'amount' : IDL.Float64,
  });
  const Worker = IDL.Record({
    'salary' : IDL.Float64,
    'payments' : IDL.Vec(WorkerPayment),
    'joinDate' : Time,
    'name' : IDL.Text,
    'phone' : IDL.Text,
  });
  
  return IDL.Service({
    'addCustomer' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'addDeadPlant' : IDL.Func(
        [
          Time,
          IDL.Nat,
          IDL.Text,
          IDL.Nat,
          IDL.Float64,
          IDL.Float64,
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
        ],
        [IDL.Nat],
        [],
      ),
    'addExpense' : IDL.Func(
        [Time, IDL.Text, IDL.Text, IDL.Float64, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'addPlant' : IDL.Func(
        [
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Float64,
          IDL.Float64,
          IDL.Nat,
          IDL.Opt(IDL.Text),
        ],
        [IDL.Nat],
        [],
      ),
    'addPot' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Float64,
          IDL.Float64,
          IDL.Nat,
          IDL.Opt(IDL.Text),
        ],
        [IDL.Nat],
        [],
      ),
    'addPropagationPlant' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Float64,
          IDL.Float64,
          IDL.Nat,
          IDL.Opt(IDL.Text),
        ],
        [IDL.Nat],
        [],
      ),
    'addWorker' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Float64, Time],
        [IDL.Nat],
        [],
      ),
    'addWorkerPayment' : IDL.Func(
        [IDL.Nat, Time, IDL.Float64, IDL.Text],
        [],
        [],
      ),
    'createSale' : IDL.Func(
        [
          IDL.Text,
          Time,
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Bool,
          IDL.Vec(SaleItem),
          IDL.Float64,
          IDL.Float64,
          IDL.Opt(IDL.Text),
          IDL.Float64,
          IDL.Text,
          IDL.Opt(IDL.Text),
        ],
        [],
        [],
      ),
    'deletePlant' : IDL.Func([IDL.Nat], [], []),
    'deletePot' : IDL.Func([IDL.Nat], [], []),
    'deletePropagationPlant' : IDL.Func([IDL.Nat], [], []),
    'getAllCustomers' : IDL.Func([], [IDL.Vec(Customer)], ['query']),
    'getAllDeadPlants' : IDL.Func([], [IDL.Vec(DeadPlant)], ['query']),
    'getAllExpenses' : IDL.Func([], [IDL.Vec(Expense)], ['query']),
    'getAllPlants' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getAllPots' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getAllPropagationPlants' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getAllSales' : IDL.Func([], [IDL.Vec(Sale)], ['query']),
    'getAllWorkers' : IDL.Func([], [IDL.Vec(Worker)], ['query']),
    'getLowStockPlants' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'updateCustomerStats' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Float64, IDL.Float64],
        [],
        [],
      ),
    'updatePlant' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Float64,
          IDL.Float64,
          IDL.Nat,
          IDL.Opt(IDL.Text),
        ],
        [],
        [],
      ),
    'updatePot' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Float64,
          IDL.Float64,
          IDL.Nat,
          IDL.Opt(IDL.Text),
        ],
        [],
        [],
      ),
    'updatePropagationPlant' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Float64,
          IDL.Float64,
          IDL.Nat,
          IDL.Opt(IDL.Text),
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };