/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Product {
    id: bigint;
    status: ProductStatus;
    purchasePrice: number;
    stockQty: bigint;
    name: string;
    color?: string;
    size?: string;
    parentPlant?: bigint;
    sellingPrice: number;
    productType: ProductType;
    potType?: string;
    category?: string;
    image?: string;
    propagationType?: string;
    dateAdded: Time;
}
export interface Expense {
    date: Time;
    description: string;
    paymentMode: string;
    category: string;
    amount: number;
}
export interface Customer {
    name: string;
    totalPurchases: bigint;
    totalSpent: number;
    phone: string;
    totalDiscount: number;
}
export type Time = bigint;
export interface DeadPlant {
    date: Time;
    deadQuantity: bigint;
    purchasePriceEach: number;
    totalLoss: number;
    productId: bigint;
    productName: string;
    notes?: string;
    photo?: string;
    reason: string;
}
export interface Sale {
    customerName?: string;
    isWalkIn: boolean;
    customerPhone?: string;
    date: Time;
    totalPaid: number;
    discountReason?: string;
    discount: number;
    paymentMode: string;
    items: Array<SaleItem>;
    billNo: string;
    subtotal: number;
    savedMessage?: string;
}
export interface Worker {
    salary: number;
    payments: Array<WorkerPayment>;
    joinDate: Time;
    name: string;
    phone: string;
}
export interface SaleItem {
    total: number;
    productId: bigint;
    productName: string;
    quantity: bigint;
    price: number;
}
export interface WorkerPayment {
    date: Time;
    paymentMode: string;
    amount: number;
}
export enum ProductStatus {
    active = "active",
    discontinued = "discontinued",
    outOfStock = "outOfStock"
}
export enum ProductType {
    pot = "pot",
    propagation = "propagation",
    plant = "plant"
}
export interface backendInterface {
    addCustomer(name: string, phone: string): Promise<void>;
    addDeadPlant(date: Time, productId: bigint, productName: string, deadQuantity: bigint, purchasePriceEach: number, totalLoss: number, reason: string, notes: string | null, photo: string | null): Promise<bigint>;
    addExpense(date: Time, category: string, description: string, amount: number, paymentMode: string): Promise<bigint>;
    addPlant(name: string, category: string | null, purchasePrice: number, sellingPrice: number, stockQty: bigint, image: string | null): Promise<bigint>;
    addPot(name: string, size: string, color: string, potType: string, purchasePrice: number, sellingPrice: number, stockQty: bigint, image: string | null): Promise<bigint>;
    addPropagationPlant(name: string, propagationType: string, parentPlant: bigint, actualCost: number, sellingPrice: number, stockQty: bigint, image: string | null): Promise<bigint>;
    addWorker(name: string, phone: string, salary: number, joinDate: Time): Promise<bigint>;
    addWorkerPayment(workerId: bigint, date: Time, amount: number, paymentMode: string): Promise<void>;
    createSale(billNo: string, date: Time, customerName: string | null, customerPhone: string | null, isWalkIn: boolean, items: Array<SaleItem>, subtotal: number, discount: number, discountReason: string | null, totalPaid: number, paymentMode: string, savedMessage: string | null): Promise<void>;
    deletePlant(id: bigint): Promise<void>;
    deletePot(id: bigint): Promise<void>;
    deletePropagationPlant(id: bigint): Promise<void>;
    getAllCustomers(): Promise<Array<Customer>>;
    getAllDeadPlants(): Promise<Array<DeadPlant>>;
    getAllExpenses(): Promise<Array<Expense>>;
    getAllPlants(): Promise<Array<Product>>;
    getAllPots(): Promise<Array<Product>>;
    getAllPropagationPlants(): Promise<Array<Product>>;
    getAllSales(): Promise<Array<Sale>>;
    getAllWorkers(): Promise<Array<Worker>>;
    getLowStockPlants(): Promise<Array<Product>>;
    updateCustomerStats(phone: string, purchases: bigint, spent: number, discount: number): Promise<void>;
    updatePlant(id: bigint, name: string, category: string | null, purchasePrice: number, sellingPrice: number, stockQty: bigint, image: string | null): Promise<void>;
    updatePot(id: bigint, name: string, size: string, color: string, potType: string, purchasePrice: number, sellingPrice: number, stockQty: bigint, image: string | null): Promise<void>;
    updatePropagationPlant(id: bigint, name: string, propagationType: string, parentPlant: bigint, actualCost: number, sellingPrice: number, stockQty: bigint, image: string | null): Promise<void>;
}
import type { DeadPlant as _DeadPlant, Product as _Product, ProductStatus as _ProductStatus, ProductType as _ProductType, Sale as _Sale, SaleItem as _SaleItem, Time as _Time } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addCustomer(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addCustomer(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addCustomer(arg0, arg1);
            return result;
        }
    }
    async addDeadPlant(arg0: Time, arg1: bigint, arg2: string, arg3: bigint, arg4: number, arg5: number, arg6: string, arg7: string | null, arg8: string | null): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addDeadPlant(arg0, arg1, arg2, arg3, arg4, arg5, arg6, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg7), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg8));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addDeadPlant(arg0, arg1, arg2, arg3, arg4, arg5, arg6, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg7), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg8));
            return result;
        }
    }
    async addExpense(arg0: Time, arg1: string, arg2: string, arg3: number, arg4: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addExpense(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addExpense(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async addPlant(arg0: string, arg1: string | null, arg2: number, arg3: number, arg4: bigint, arg5: string | null): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addPlant(arg0, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg1), arg2, arg3, arg4, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg5));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addPlant(arg0, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg1), arg2, arg3, arg4, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg5));
            return result;
        }
    }
    async addPot(arg0: string, arg1: string, arg2: string, arg3: string, arg4: number, arg5: number, arg6: bigint, arg7: string | null): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addPot(arg0, arg1, arg2, arg3, arg4, arg5, arg6, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg7));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addPot(arg0, arg1, arg2, arg3, arg4, arg5, arg6, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg7));
            return result;
        }
    }
    async addPropagationPlant(arg0: string, arg1: string, arg2: bigint, arg3: number, arg4: number, arg5: bigint, arg6: string | null): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addPropagationPlant(arg0, arg1, arg2, arg3, arg4, arg5, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg6));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addPropagationPlant(arg0, arg1, arg2, arg3, arg4, arg5, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg6));
            return result;
        }
    }
    async addWorker(arg0: string, arg1: string, arg2: number, arg3: Time): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addWorker(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addWorker(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async addWorkerPayment(arg0: bigint, arg1: Time, arg2: number, arg3: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addWorkerPayment(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addWorkerPayment(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async createSale(arg0: string, arg1: Time, arg2: string | null, arg3: string | null, arg4: boolean, arg5: Array<SaleItem>, arg6: number, arg7: number, arg8: string | null, arg9: number, arg10: string, arg11: string | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createSale(arg0, arg1, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg3), arg4, arg5, arg6, arg7, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg8), arg9, arg10, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg11));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createSale(arg0, arg1, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg3), arg4, arg5, arg6, arg7, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg8), arg9, arg10, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg11));
            return result;
        }
    }
    async deletePlant(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deletePlant(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deletePlant(arg0);
            return result;
        }
    }
    async deletePot(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deletePot(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deletePot(arg0);
            return result;
        }
    }
    async deletePropagationPlant(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deletePropagationPlant(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deletePropagationPlant(arg0);
            return result;
        }
    }
    async getAllCustomers(): Promise<Array<Customer>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllCustomers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllCustomers();
            return result;
        }
    }
    async getAllDeadPlants(): Promise<Array<DeadPlant>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllDeadPlants();
                return from_candid_vec_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllDeadPlants();
            return from_candid_vec_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllExpenses(): Promise<Array<Expense>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllExpenses();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllExpenses();
            return result;
        }
    }
    async getAllPlants(): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPlants();
                return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPlants();
            return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllPots(): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPots();
                return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPots();
            return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllPropagationPlants(): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPropagationPlants();
                return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPropagationPlants();
            return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllSales(): Promise<Array<Sale>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllSales();
                return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllSales();
            return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllWorkers(): Promise<Array<Worker>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllWorkers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllWorkers();
            return result;
        }
    }
    async getLowStockPlants(): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLowStockPlants();
                return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLowStockPlants();
            return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateCustomerStats(arg0: string, arg1: bigint, arg2: number, arg3: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCustomerStats(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCustomerStats(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async updatePlant(arg0: bigint, arg1: string, arg2: string | null, arg3: number, arg4: number, arg5: bigint, arg6: string | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePlant(arg0, arg1, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg2), arg3, arg4, arg5, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg6));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePlant(arg0, arg1, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg2), arg3, arg4, arg5, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg6));
            return result;
        }
    }
    async updatePot(arg0: bigint, arg1: string, arg2: string, arg3: string, arg4: string, arg5: number, arg6: number, arg7: bigint, arg8: string | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePot(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg8));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePot(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg8));
            return result;
        }
    }
    async updatePropagationPlant(arg0: bigint, arg1: string, arg2: string, arg3: bigint, arg4: number, arg5: number, arg6: bigint, arg7: string | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePropagationPlant(arg0, arg1, arg2, arg3, arg4, arg5, arg6, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg7));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePropagationPlant(arg0, arg1, arg2, arg3, arg4, arg5, arg6, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg7));
            return result;
        }
    }
}
function from_candid_DeadPlant_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DeadPlant): DeadPlant {
    return from_candid_record_n4(_uploadFile, _downloadFile, value);
}
function from_candid_ProductStatus_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ProductStatus): ProductStatus {
    return from_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function from_candid_ProductType_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ProductType): ProductType {
    return from_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function from_candid_Product_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Product): Product {
    return from_candid_record_n8(_uploadFile, _downloadFile, value);
}
function from_candid_Sale_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Sale): Sale {
    return from_candid_record_n16(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    customerName: [] | [string];
    isWalkIn: boolean;
    customerPhone: [] | [string];
    date: _Time;
    totalPaid: number;
    discountReason: [] | [string];
    discount: number;
    paymentMode: string;
    items: Array<_SaleItem>;
    billNo: string;
    subtotal: number;
    savedMessage: [] | [string];
}): {
    customerName?: string;
    isWalkIn: boolean;
    customerPhone?: string;
    date: Time;
    totalPaid: number;
    discountReason?: string;
    discount: number;
    paymentMode: string;
    items: Array<SaleItem>;
    billNo: string;
    subtotal: number;
    savedMessage?: string;
} {
    return {
        customerName: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.customerName)),
        isWalkIn: value.isWalkIn,
        customerPhone: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.customerPhone)),
        date: value.date,
        totalPaid: value.totalPaid,
        discountReason: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.discountReason)),
        discount: value.discount,
        paymentMode: value.paymentMode,
        items: value.items,
        billNo: value.billNo,
        subtotal: value.subtotal,
        savedMessage: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.savedMessage))
    };
}
function from_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    date: _Time;
    deadQuantity: bigint;
    purchasePriceEach: number;
    totalLoss: number;
    productId: bigint;
    productName: string;
    notes: [] | [string];
    photo: [] | [string];
    reason: string;
}): {
    date: Time;
    deadQuantity: bigint;
    purchasePriceEach: number;
    totalLoss: number;
    productId: bigint;
    productName: string;
    notes?: string;
    photo?: string;
    reason: string;
} {
    return {
        date: value.date,
        deadQuantity: value.deadQuantity,
        purchasePriceEach: value.purchasePriceEach,
        totalLoss: value.totalLoss,
        productId: value.productId,
        productName: value.productName,
        notes: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.notes)),
        photo: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.photo)),
        reason: value.reason
    };
}
function from_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _ProductStatus;
    purchasePrice: number;
    stockQty: bigint;
    name: string;
    color: [] | [string];
    size: [] | [string];
    parentPlant: [] | [bigint];
    sellingPrice: number;
    productType: _ProductType;
    potType: [] | [string];
    category: [] | [string];
    image: [] | [string];
    propagationType: [] | [string];
    dateAdded: _Time;
}): {
    id: bigint;
    status: ProductStatus;
    purchasePrice: number;
    stockQty: bigint;
    name: string;
    color?: string;
    size?: string;
    parentPlant?: bigint;
    sellingPrice: number;
    productType: ProductType;
    potType?: string;
    category?: string;
    image?: string;
    propagationType?: string;
    dateAdded: Time;
} {
    return {
        id: value.id,
        status: from_candid_ProductStatus_n9(_uploadFile, _downloadFile, value.status),
        purchasePrice: value.purchasePrice,
        stockQty: value.stockQty,
        name: value.name,
        color: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.color)),
        size: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.size)),
        parentPlant: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.parentPlant)),
        sellingPrice: value.sellingPrice,
        productType: from_candid_ProductType_n12(_uploadFile, _downloadFile, value.productType),
        potType: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.potType)),
        category: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.category)),
        image: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.image)),
        propagationType: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.propagationType)),
        dateAdded: value.dateAdded
    };
}
function from_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    active: null;
} | {
    discontinued: null;
} | {
    outOfStock: null;
}): ProductStatus {
    return "active" in value ? ProductStatus.active : "discontinued" in value ? ProductStatus.discontinued : "outOfStock" in value ? ProductStatus.outOfStock : value;
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pot: null;
} | {
    propagation: null;
} | {
    plant: null;
}): ProductType {
    return "pot" in value ? ProductType.pot : "propagation" in value ? ProductType.propagation : "plant" in value ? ProductType.plant : value;
}
function from_candid_vec_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Sale>): Array<Sale> {
    return value.map((x)=>from_candid_Sale_n15(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_DeadPlant>): Array<DeadPlant> {
    return value.map((x)=>from_candid_DeadPlant_n3(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Product>): Array<Product> {
    return value.map((x)=>from_candid_Product_n7(_uploadFile, _downloadFile, x));
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
